[project]
name = "toolbox"
version = "0.1.0"
description = "Common code and assorted tools for Ghostty Bot"
license = "MIT"
authors = [{ name = "trag1c", email = "dev@jakubr.me" }]
dependencies = ["discord-py>=2.6.3", "httpx>=0.28.1", "loguru>=0.7.0"]

[dependency-groups]
dev = ["githubkit>=0.14.0", "hypothesis>=6.148.9"]

[build-system]
requires = ["uv_build>=0.9.17,<0.10"]
build-backend = "uv_build"
